name: 'Issue Labels'

on:
  issues:
    types: [opened, reopened, closed]

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Check Labels - https://github.com/mheap/github-action-required-labels
  add_label_user_close_check:
    name: Close Issue Label - Check
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 0
          labels: "Bug, Enhancement"

  # Add  Labels  - https://github.com/actions-ecosystem/action-add-labels
  add_label_user_close_act:
    name: Close Issue Label - Cancel
    needs: add_label_user_close_check
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Cancelled
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Check Similarity - https://github.com/actions-cool/issues-similarity-analysis
  similarity_analysis:
    name: Check Similarity
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'opened'
    steps:
      - uses: actions-cool/issues-similarity-analysis@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          since-days: 450
          filter-threshold: 0.45
          comment-title: '### Similarity Analysis'
          comment-body: '[Score: ${similarity}] #${number}'
          show-footer: false

  # Add Labels - https://github.com/actions-ecosystem/action-add-labels
  add_label_user_open:
    name: Default Issue Label
    needs: similarity_analysis
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Triage
          github_token: ${{ secrets.GITHUB_TOKEN }}

  add_label_base_reopen:
    name: Reopen Issue Label - Base
    runs-on: ubuntu-20.04

    if: github.actor == 'dakanji' && github.event.action == 'reopened'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            Not-Planned
            Tagged
            Stale
            Cannot-Replicate
            Known-Issue
            Incomplete
            Uncertain
            Unclear
            Invalid
            Queries
            Unclear
          github_token: ${{ secrets.GITHUB_TOKEN }}

  add_label_user_reopen:
    name: Reopen Issue Label - User
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'reopened'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Triage
          github_token: ${{ secrets.GITHUB_TOKEN }}

  add_label_user_open_enhance:
    name: Enhancement Request Label
    needs: similarity_analysis
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'opened' && contains(github.event.issue.body, 'Suggested Feature') && contains(github.event.issue.body, 'Background Information') && contains(github.event.issue.body, 'Additional Context')
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Enhancement
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Del Labels - https://github.com/actions-ecosystem/action-remove-labels
  del_label_user_reopen:
    name: Remove Cancelled Label
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'reopened'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Cancelled
          github_token: ${{ secrets.GITHUB_TOKEN }}

  del_label_user_close:
    name: Remove Misc Labels
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            Stale
            Tagged
            Triage
            Cannot-Replicate
            Known-Issue
            Incomplete
            Uncertain
            Unclear
            Invalid
            Queries
            Unclear
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Check Labels - https://github.com/mheap/github-action-required-labels
  bounce_bug_check1:
    name: Bounce Bug - Check1
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "Bug"

  # Reopen Issue - https://github.com/actions-cool/issues-helper
  bounce_bug_act1:
    name: Bounce Bug - Act1
    needs: [bounce_bug_check1]
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'open-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}

  # Reopen Issue - https://github.com/actions-cool/issues-helper
  bounce_bug_act2:
    name: Bounce Bug - Act2
    needs: [bounce_bug_act1]
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Please do not close accepted confirmed bugs in future.
            Work has aleady started, or is planned, on such items.

  # Check Labels - https://github.com/mheap/github-action-required-labels
  bounce_enhance_check1:
    name: Bounce Enhance - Check1
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "Enhancement"

  # Check Labels - https://github.com/mheap/github-action-required-labels
  bounce_enhance_check2:
    name: Bounce Enhance - Check2
    needs: [bounce_enhance_check1]
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "Accepted"

  # Reopen Issue - https://github.com/actions-cool/issues-helper
  bounce_enhance_act1:
    name: Bounce Enhance - Act1
    needs: [bounce_enhance_check2]
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'open-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}

  # Reopen Issue - https://github.com/actions-cool/issues-helper
  bounce_enhance_act2:
    name: Bounce Enhance - Act2
    needs: [bounce_enhance_act1]
    runs-on: ubuntu-20.04

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Please do not close accepted `Accepted` Enhancements.
            Work has aleady started, or is planned, on such items.
