name: 'Issue Labels'

on:
  issues:
    types: [opened, reopened, closed]

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Check Labels - https://github.com/mheap/github-action-required-labels
  add_label_user_close_check:
    name: Close Issue Label - Check
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 0
          labels: "Bug, Enhancement"

  # Add  Labels  - https://github.com/actions-ecosystem/action-add-labels
  add_label_user_close_act:
    name: Close Issue Label - Act
    needs: add_label_user_close_check
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: Cancelled
          github_token: ${{ github.token }}

  # Check Similarity - https://github.com/actions-cool/issues-similarity-analysis
  similarity_analysis:
    name: Check Similarity
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'opened'
    steps:
      - uses: actions-cool/issues-similarity-analysis@v1.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          since-days: 270
          filter-threshold: 0.6
          comment-title: '### Similarity Analysis'
          comment-body: '[Score: ${similarity}] #${number}'
          show-footer: false

  # Add Labels - https://github.com/actions-ecosystem/action-add-labels
  add_label_user_open:
    name: Default Issue Label
    needs: similarity_analysis
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'opened'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: Pending
          github_token: ${{ github.token }}

  add_label_user_reopen:
    name: Reopen Issue Label
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'reopened'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: Pending
          github_token: ${{ github.token }}

  add_label_user_open_enhance:
    name: Enhancement Request Label
    needs: similarity_analysis
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'opened' && contains(github.event.issue.body, 'Suggested Feature') && contains(github.event.issue.body, 'Background Information') && contains(github.event.issue.body, 'Additional Context')
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: Enhancement
          github_token: ${{ github.token }}

  # Del Labels - https://github.com/actions-ecosystem/action-remove-labels
  del_label_user_reopen:
    name: Remove Cancelled Label
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'reopened'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: Cancelled
          github_token: ${{ github.token }}

  del_label_user_close:
    name: Remove Misc Labels
    runs-on: ubuntu-latest

    if: github.actor != 'dakanji' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: |
            Tagged
            Pending
            Incomplete
            Invalid
            Queries
            Unclear
          github_token: ${{ github.token }}
