
name: 'Auto Labels'

on:
  workflow_dispatch:
  issues:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write

jobs:

  # Auto Labels - https://github.com/dessant/label-actions
  auto_labels:
    name: Handle Labels
    runs-on: ubuntu-20.04

    steps:
      - uses: dessant/label-actions@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: '.github/label-config.yml'
          process-only: ''
